import { Book, Testament } from './types';

export const BIBLE_BOOKS: Book[] = [
  // --- ANTIGO TESTAMENTO ---
  { name: 'Gênesis', chapters: 50, testament: Testament.OLD },
  { name: 'Êxodo', chapters: 40, testament: Testament.OLD },
  { name: 'Levítico', chapters: 27, testament: Testament.OLD },
  { name: 'Números', chapters: 36, testament: Testament.OLD },
  { name: 'Deuteronômio', chapters: 34, testament: Testament.OLD },
  { name: 'Josué', chapters: 24, testament: Testament.OLD },
  { name: 'Juízes', chapters: 21, testament: Testament.OLD },
  { name: 'Rute', chapters: 4, testament: Testament.OLD },
  { name: '1 Samuel', chapters: 31, testament: Testament.OLD },
  { name: '2 Samuel', chapters: 24, testament: Testament.OLD },
  { name: '1 Reis', chapters: 22, testament: Testament.OLD },
  { name: '2 Reis', chapters: 25, testament: Testament.OLD },
  { name: '1 Crônicas', chapters: 29, testament: Testament.OLD },
  { name: '2 Crônicas', chapters: 36, testament: Testament.OLD },
  { name: 'Esdras', chapters: 10, testament: Testament.OLD },
  { name: 'Neemias', chapters: 13, testament: Testament.OLD },
  { name: 'Ester', chapters: 10, testament: Testament.OLD },
  { name: 'Jó', chapters: 42, testament: Testament.OLD },
  { name: 'Salmos', chapters: 150, testament: Testament.OLD },
  { name: 'Provérbios', chapters: 31, testament: Testament.OLD },
  { name: 'Eclesiastes', chapters: 12, testament: Testament.OLD },
  { name: 'Cânticos', chapters: 8, testament: Testament.OLD },
  { name: 'Isaías', chapters: 66, testament: Testament.OLD },
  { name: 'Jeremias', chapters: 52, testament: Testament.OLD },
  { name: 'Lamentações', chapters: 5, testament: Testament.OLD },
  { name: 'Ezequiel', chapters: 48, testament: Testament.OLD },
  { name: 'Daniel', chapters: 12, testament: Testament.OLD },
  { name: 'Oseias', chapters: 14, testament: Testament.OLD },
  { name: 'Joel', chapters: 3, testament: Testament.OLD },
  { name: 'Amós', chapters: 9, testament: Testament.OLD },
  { name: 'Obadias', chapters: 1, testament: Testament.OLD },
  { name: 'Jonas', chapters: 4, testament: Testament.OLD },
  { name: 'Miqueias', chapters: 7, testament: Testament.OLD },
  { name: 'Naum', chapters: 3, testament: Testament.OLD },
  { name: 'Habacuque', chapters: 3, testament: Testament.OLD },
  { name: 'Sofonias', chapters: 3, testament: Testament.OLD },
  { name: 'Ageu', chapters: 2, testament: Testament.OLD },
  { name: 'Zacarias', chapters: 14, testament: Testament.OLD },
  { name: 'Malaquias', chapters: 4, testament: Testament.OLD },

  // --- NOVO TESTAMENTO ---
  { name: 'Mateus', chapters: 28, testament: Testament.NEW },
  { name: 'Marcos', chapters: 16, testament: Testament.NEW },
  { name: 'Lucas', chapters: 24, testament: Testament.NEW },
  { name: 'João', chapters: 21, testament: Testament.NEW },
  { name: 'Atos', chapters: 28, testament: Testament.NEW },
  { name: 'Romanos', chapters: 16, testament: Testament.NEW },
  { name: '1 Coríntios', chapters: 16, testament: Testament.NEW },
  { name: '2 Coríntios', chapters: 13, testament: Testament.NEW },
  { name: 'Gálatas', chapters: 6, testament: Testament.NEW },
  { name: 'Efésios', chapters: 6, testament: Testament.NEW },
  { name: 'Filipenses', chapters: 4, testament: Testament.NEW },
  { name: 'Colossenses', chapters: 4, testament: Testament.NEW },
  { name: '1 Tessalonicenses', chapters: 5, testament: Testament.NEW },
  { name: '2 Tessalonicenses', chapters: 3, testament: Testament.NEW },
  { name: '1 Timóteo', chapters: 6, testament: Testament.NEW },
  { name: '2 Timóteo', chapters: 4, testament: Testament.NEW },
  { name: 'Tito', chapters: 3, testament: Testament.NEW },
  { name: 'Filemom', chapters: 1, testament: Testament.NEW },
  { name: 'Hebreus', chapters: 13, testament: Testament.NEW },
  { name: 'Tiago', chapters: 5, testament: Testament.NEW },
  { name: '1 Pedro', chapters: 5, testament: Testament.NEW },
  { name: '2 Pedro', chapters: 3, testament: Testament.NEW },
  { name: '1 João', chapters: 5, testament: Testament.NEW },
  { name: '2 João', chapters: 1, testament: Testament.NEW },
  { name: '3 João', chapters: 1, testament: Testament.NEW },
  { name: 'Judas', chapters: 1, testament: Testament.NEW },
  { name: 'Apocalipse', chapters: 22, testament: Testament.NEW },
];